import { Open_Sans } from "next/font/google";

import Header from "@components/common/Header";

import Swr from "@context/Swr";
import Session from "@context/Session";

import "./globals.css";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={sans.className}>
      <body className="flex flex-col w-full max-w-screen-lg mx-auto ">
        <Swr>
          <Session>
            <Header />
            <main className="flex justify-center grow bg-neutral-50">
              {children}
            </main>
          </Session>
        </Swr>
      </body>
    </html>
  );
}
