import { Open_Sans } from "next/font/google";

import Header from "@components/common/Header";

import Session from "@context/Session";
import "./globals.css";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={sans.className}>
      <body className="flex flex-col w-full max-w-screen-lg mx-auto ">
        <Session>
          <Header />
          <main className="grow">{children}</main>
        </Session>
      </body>
    </html>
  );
}
